load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = [
    "//iamf/api:__subpackages__",
    "//iamf/include:__subpackages__",
])

# keep-sorted start block=yes prefix_order=cc_library newline_separated=yes
cc_library(
    name = "iamf_tools_api_types",
    srcs = ["iamf_tools_api_types.cc"],
    hdrs = [
        "//iamf/include/iamf_tools:iamf_tools_api_types_header",
    ],
)

# keep-sorted end
