package(default_visibility = ["//iamf/api:__subpackages__"])

# keep-sorted start block=yes prefix_order=cc_library newline_separated=yes
cc_library(
    name = "types",
    hdrs = ["types.h"],
)

# keep-sorted end
