package(default_visibility = ["//iamf/api:__subpackages__"])

# keep-sorted start block=yes prefix_order=cc_library newline_separated=yes
cc_library(
    name = "iamf_tools_api_types",
    srcs = ["iamf_tools_api_types.cc"],
    hdrs = ["iamf_tools_api_types.h"],
)

# keep-sorted end
