package(default_visibility = [
    "//iamf/api/conversion/tests:__pkg__",
])

# keep-sorted start block=yes prefix_order=cc_library newline_separated=yes
cc_library(
    name = "mix_presentation_conversion",
    srcs = ["mix_presentation_conversion.cc"],
    hdrs = ["mix_presentation_conversion.h"],
    deps = [
        "//iamf/api:types",
        "//iamf/obu:mix_presentation",
        "@com_google_absl//absl/log",
    ],
)
# keep-sorted end
