filegroup(
    name = "iamf_decoder_header",
    srcs = ["iamf_decoder.h"],
    visibility = [
        "//iamf/api/decoder:__pkg__",
    ],
)

filegroup(
    name = "iamf_tools_api_types_header",
    srcs = ["iamf_tools_api_types.h"],
    visibility = [
        "//iamf/api:__pkg__",
    ],
)
