# Copyright (c) 2024, Alliance for Open Media. All rights reserved
#
# This source code is subject to the terms of the BSD 3-Clause Clear License
# and the Alliance for Open Media Patent License 1.0. If the BSD 3-Clause Clear
# License was not distributed with this source code in the LICENSE file, you
# can obtain it at www.aomedia.org/license/software-license/bsd-3-c-c. If the
# Alliance for Open Media Patent License 1.0 was not distributed with this
# source code in the PATENTS file, you can obtain it at
# www.aomedia.org/license/patent.

# proto-file: iamf/cli/proto/user_metadata.proto
# proto-message: UserMetadata

test_vector_metadata {
  human_readable_description: "Template. Fill in `file_name_prefix` and `wav_filename` to encode a file."
  file_name_prefix: "TEMPLATE"
  is_valid: true
}

audio_frame_metadata {
  wav_filename: "TEMPLATE_FOA.wav"
  samples_to_trim_at_end_includes_padding: false
  samples_to_trim_at_start_includes_codec_delay: false
  samples_to_trim_at_end: 0
  samples_to_trim_at_start: 0
  audio_element_id: 300
  channel_metadatas: [
    { channel_id: 0 channel_label: CHANNEL_LABEL_A_0 },
    { channel_id: 1 channel_label: CHANNEL_LABEL_A_1 },
    { channel_id: 2 channel_label: CHANNEL_LABEL_A_2 },
    { channel_id: 3 channel_label: CHANNEL_LABEL_A_3 }
  ]
}

ia_sequence_header_metadata {
  primary_profile: PROFILE_VERSION_SIMPLE
  additional_profile: PROFILE_VERSION_SIMPLE
}

codec_config_metadata {
  codec_config_id: 200
  codec_config {
    codec_id: CODEC_ID_LPCM
    num_samples_per_frame: 1024
    decoder_config_lpcm {
      sample_format_flags: LPCM_LITTLE_ENDIAN
      sample_size: 24
      sample_rate: 48000
    }
  }
}

audio_element_metadata {
  audio_element_id: 300
  audio_element_type: AUDIO_ELEMENT_SCENE_BASED
  reserved: 0
  codec_config_id: 200
  num_substreams: 4
  audio_substream_ids: [0, 1, 2, 3]
  num_parameters: 0
  ambisonics_config {
    ambisonics_mode: AMBISONICS_MODE_MONO
    ambisonics_mono_config {
      output_channel_count: 4
      substream_count: 4
      channel_mapping: [0, 1, 2, 3]
    }
  }
}

mix_presentation_metadata {
  mix_presentation_id: 42
  count_label: 1
  annotations_language: ["en-us"]
  localized_presentation_annotations: ["Default Mix Presentation"]
  num_sub_mixes: 1
  sub_mixes {
    num_audio_elements: 1
    audio_elements {
      audio_element_id: 300
      localized_element_annotations: ["First-order Ambisonics"]
      rendering_config {
        headphones_rendering_mode: HEADPHONES_RENDERING_MODE_BINAURAL
      }
      element_mix_gain {
        param_definition {
          parameter_id: 999  # Non-existent; default will be used
          parameter_rate: 48000
          param_definition_mode: 1
          reserved: 0
        }
        default_mix_gain: 0
      }
    }
    output_mix_gain {
      param_definition {
        parameter_id: 998  # Non-existent; default will be used
        parameter_rate: 48000
        param_definition_mode: 1
        reserved: 0
      }
      default_mix_gain: 0
    }
    num_layouts: 1
    layouts {
      loudness_layout {
        layout_type: LAYOUT_TYPE_LOUDSPEAKERS_SS_CONVENTION
        ss_layout {
          sound_system: SOUND_SYSTEM_A_0_2_0
          reserved: 0
        }
      }
      loudness {
        info_type_bit_masks: []
      }
    }
  }
}

temporal_delimiter_metadata {
  enable_temporal_delimiters: false
}
