package(default_visibility = [
    "//iamf/cli:__subpackages__",
    "//iamf/include/iamf_tools:__subpackages__",
])

# keep-sorted start block=yes prefix_order=filegroup newline_separated=yes
filegroup(
    name = "textprotos",
    srcs = glob(["*.textproto"]),
)

# keep-sorted end
