# keep-sorted start block=yes prefix_order=cc_test newline_separated=yes
cc_test(
    name = "mix_presentation_conversion_test",
    srcs = ["mix_presentation_conversion_test.cc"],
    deps = [
        "//iamf/api:types",
        "//iamf/api/conversion:mix_presentation_conversion",
        "//iamf/obu:mix_presentation",
        "@com_google_absl//absl/status:status_matchers",
        "@com_google_googletest//:gtest_main",
    ],
)
# keep-sorted end
