cc_test(
    name = "channel_label_utils_test",
    srcs = ["channel_label_utils_test.cc"],
    deps = [
        "//iamf/cli:channel_label",
        "//iamf/cli/proto_conversion:channel_label_utils",
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/status:status_matchers",
        "@com_google_absl//absl/strings:string_view",
        "@com_google_googletest//:gtest_main",
    ],
)
