package(default_visibility = [
    "//iamf/api:__subpackages__",
    "//iamf/cli:__subpackages__",
])

cc_library(
    name = "codec_config_obu_metadata_builder",
    srcs = ["codec_config_obu_metadata_builder.cc"],
    hdrs = ["codec_config_obu_metadata_builder.h"],
    deps = [
        "//iamf/cli/proto:codec_config_cc_proto",
        "//iamf/obu:types",
    ],
)
