name: build

on: [push, pull_request]

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/iamf-tools-builder
  macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/iamf-tools-builder
  macos-amd64:
    runs-on: macos-12
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/iamf-tools-builder
