# keep-sorted start block=yes prefix_order=cc_test newline_separated=yes
cc_test(
    name = "iamf_decoder_test",
    srcs = ["iamf_decoder_test.cc"],
    deps = [
        "//iamf/api:iamf_decoder",
        "@com_google_googletest//:gtest_main",
    ],
)

# keep-sorted end
